### PR TITLE
Update to 1.20.6

### PR DESCRIPTION
**Pull request by DarkCows**

### CODE REVIEW

**Comment by venaminecraft** [comment]
Can you update the mod please to 1.20.6 @DarkCows? 😄

**Comment by DarkCows** [comment]
> Can you update the mod please to 1.20.6 @DarkCows? 😄

I updated the mod, you can download the source using 'git clone https://github.com/DarkCows/FastChest.git' then building the project using './gradlew build'. The jar file will then be in build > libs

**Comment by venaminecraft** [comment]
Thank you!!

**Comment by FakeDomi** [comment]
I don't understand the point of this PR, you are literally just bumping numbers. The 1.20.2+ build still works on 1.20.6

**Comment by DarkCows** [comment]
> I don't understand the point of this PR, you are literally just bumping numbers. The 1.20.2+ build still works on 1.20.6

You are right, It was telling me that it was incompatable but I retested and just using the 1.20.2 version works

**Pull request closed without merging**
